In [4]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

C:\Users\jacob\AppData\Roaming\Python\Python313\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

In [5]:
df=pd.read_csv("insurance_data.csv")
df
df.head()

   age  affordability  have_insurance
0   22              1               0
1   25              0               0
2   47              1               1
3   52              0               0
4   46              1               1

In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df[['age','affordability']],df.have_insurance,test_size=0.2,random_state=25)

In [31]:
x_train

    age  affordability
1    25              0
9    61              1
12   27              0
0    22              1
5    56              1
2    47              1
7    60              0
6    55              0
10   18              1
4    46              1

In [10]:
x_test

    age  affordability
11   28              1
8    62              1
3    52              0

In [12]:
y_train

1     0
9     1
12    1
0     0
5     1
2     1
7     1
6     0
10    0
4     1
Name: have_insurance, dtype: int64

In [7]:
y_test

11    0
8     1
3     0
Name: have_insurance, dtype: int64

In [12]:
x_train_scaled=x_train.copy()
x_train_scaled['age']=x_train_scaled['age']/100
x_test_scaled=x_test.copy()
x_test_scaled['age']=x_test_scaled['age']/100

In [17]:
x_train_scaled

     age  affordability
1   0.25              0
9   0.61              1
12  0.27              0
0   0.22              1
5   0.56              1
2   0.47              1
7   0.60              0
6   0.55              0
10  0.18              1
4   0.46              1

In [13]:
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(x_train_scaled,y_train,epochs=100)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 717ms/step - accuracy: 0.6000 - loss: 0.6552
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.6000 - loss: 0.6549
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.6000 - loss: 0.6547
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6000 - loss: 0.6545
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.6000 - loss: 0.6543
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.6541
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.6539
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6000 - loss: 0.6537
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6000 - loss: 0.6535
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.6000 - loss: 0.6533
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.6000 - loss: 0.6530
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6000 - loss: 0.6528
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.6526
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6000 - loss: 0.6524
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6000 - loss: 0.6522
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6000 - loss: 0.6520
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6000 - loss: 0.6518
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6000 - loss: 0.6516
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6000 - loss: 0.6514
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6000 - loss: 0.6512
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6000 - loss: 0.6510
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6000 - loss: 0.6508
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6000 - loss: 0.6506
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.6504
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6000 - loss: 0.6502
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.6501
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6000 - loss: 0.6499
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6000 - loss: 0.6497
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.6495
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6000 - loss: 0.6493
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6000 - loss: 0.6491
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.6000 - loss: 0.6489
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6000 - loss: 0.6487
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6000 - loss: 0.6485
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6000 - loss: 0.6484
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6000 - loss: 0.6482
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6000 - loss: 0.6480
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6000 - loss: 0.6478
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6000 - loss: 0.6476
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6000 - loss: 0.6475
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6000 - loss: 0.6473
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6000 - loss: 0.6471
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6000 - loss: 0.6469
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6000 - loss: 0.6467
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6000 - loss: 0.6466
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.6464
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.6000 - loss: 0.6462
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.6000 - loss: 0.6461
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6000 - loss: 0.6459
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.6457
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.6455
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.6454
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6000 - loss: 0.6452
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6000 - loss: 0.6450
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.6000 - loss: 0.6449
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6000 - loss: 0.6447
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6000 - loss: 0.6445
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6000 - loss: 0.6444
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6000 - loss: 0.6442
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6000 - loss: 0.6441
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6000 - loss: 0.6439
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6000 - loss: 0.6437
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6000 - loss: 0.6436
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6000 - loss: 0.6434
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.6433
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.6000 - loss: 0.6431
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6000 - loss: 0.6429
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6000 - loss: 0.6428
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6000 - loss: 0.6426
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6000 - loss: 0.6425
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.6423
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6000 - loss: 0.6422
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.6420
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6000 - loss: 0.6419
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.6000 - loss: 0.6417
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.6000 - loss: 0.6416
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6000 - loss: 0.6414
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6000 - loss: 0.6413
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6000 - loss: 0.6411
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6000 - loss: 0.6410
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6000 - loss: 0.6408
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6000 - loss: 0.6407
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.6000 - loss: 0.6405
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.6000 - loss: 0.6404
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6000 - loss: 0.6402
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.6401
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6000 - loss: 0.6400
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6000 - loss: 0.6398
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6000 - loss: 0.6397
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.6395
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6000 - loss: 0.6394
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.6000 - loss: 0.6393
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6000 - loss: 0.6391
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6000 - loss: 0.6390
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.6388
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6000 - loss: 0.6387
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6000 - loss: 0.6386
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6000 - loss: 0.6384
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.6000 - loss: 0.6383
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.6381

In [22]:
model.evaluate(x_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 819ms/step - accuracy: 0.3333 - loss: 0.6311

[0.6311001181602478, 0.3333333432674408]

In [14]:

model.predict(x_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

array([[0.7461817],
       [0.8028095],
       [0.5994468]], dtype=float32)

In [8]:
y_test

11    0
8     1
3     0
Name: have_insurance, dtype: int64

In [15]:
#weight and bias
#tensorflow calculation
coef,intercept=model.get_weights()
coef,intercept

(array([[0.9576369],
        [0.9050229]], dtype=float32),
 array([-0.09481066], dtype=float32))

In [16]:
#manual calculation
def sigmoid(x):
    import math
    return 1/(1+math.exp(-x))
sigmoid(18)

0.9999999847700205

In [58]:
def prediction_function(age,affordability):
    weighted_sum=coef[0]*age+coef[1]*affordability+intercept
    
    return sigmoid(weighted_sum)

In [34]:
prediction_function(0.47,1)

C:\Users\jacob\AppData\Local\Temp\ipykernel_13128\2495765867.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))

0.7790780204440064

In [52]:
def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [70]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [71]:
def gradient_descent(age, affordability, y_true, epochs, loss_thresold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)

        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
        w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true)) 

        bias_d = np.mean(y_predicted-y_true)
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d

        print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

        if loss<=loss_thresold:
            break

    return w1, w2, bias

In [72]:
gradient_descent(x_train_scaled['age'],x_train_scaled['affordability'],y_train,1000,0.4631)

Epoch:0, w1:0.9953023510435051, w2:0.9589316923292891, bias:-0.061521372825103324, loss:0.6551533000097722
Epoch:1, w1:0.993910363508503, w2:0.9229449877737186, bias:-0.11492051744354004, loss:0.6448842970323124
Epoch:2, w1:0.9954617896524035, w2:0.891582187553737, bias:-0.16108305206320225, loss:0.6371406708513416
Epoch:3, w1:0.9995943354400736, w2:0.8643542574577828, bias:-0.2008910331891214, loss:0.631323431585787
Epoch:4, w1:1.0059608511098919, w2:0.8407710950196449, bias:-0.23518694061777196, loss:0.6269452988730868
Epoch:5, w1:1.0142393890659045, w2:0.8203633699084859, bias:-0.2647501257590066, loss:0.623623723434239
Epoch:6, w1:1.0241388214587746, w2:0.8026964734931715, bias:-0.2902839303638856, loss:0.6210669192714671
Epoch:7, w1:1.0354010237980271, w2:0.7873780043929964, bias:-0.3124109840420571, loss:0.6190574546564643
Epoch:8, w1:1.0478006423445003, w2:0.7740604570653357, bias:-0.3316742051530844, loss:0.6174363139122309
Epoch:9, w1:1.0611433166350694, w2:0.7624406458419507, bias:-0.3485414091741281, loss:0.6160889395239949
Epoch:10, w1:1.075263029059126, w2:0.7522571034711266, bias:-0.36341192225109176, loss:0.6149337905685216
Epoch:11, w1:1.0900190605560538, w2:0.7432863732455065, bias:-0.3766240663902336, loss:0.6139133827799149
Epoch:12, w1:1.1052928712185945, w2:0.7353388315435946, bias:-0.3884627680741462, loss:0.6129875001786425
Epoch:13, w1:1.1209851029275484, w2:0.7282544548755421, bias:-0.3991668321564363, loss:0.6121281770497851
Epoch:14, w1:1.1370128145574554, w2:0.7218987820004413, bias:-0.408935627880515, loss:0.6113160573337637
Epoch:15, w1:1.153307001836518, w2:0.7161592079751413, bias:-0.41793507132575974, loss:0.6105377911704285
Epoch:16, w1:1.1698104164298309, w2:0.7109416715694186, bias:-0.4263028761505671, loss:0.6097841939560568
Epoch:17, w1:1.1864756761061503, w2:0.7061677498036392, bias:-0.4341530970243338, loss:0.6090489560576181
Epoch:18, w1:1.2032636451870002, w2:0.7017721449490523, bias:-0.4415800190227942, loss:0.6083277447953176
Epoch:19, w1:1.220142058385312, w2:0.6977005338148431, bias:-0.4486614597790035, loss:0.6076175829215061
Epoch:20, w1:1.2370843591791176, w2:0.6939077419747509, bias:-0.4554615551072078, loss:0.6069164203833215
Epoch:21, w1:1.2540687243758468, w2:0.6903562036071689, bias:-0.4620330970504721, loss:0.6062228403170808
Epoch:22, w1:1.2710772484085942, w2:0.6870146687147592, bias:-0.46841948841032555, loss:0.6055358577789713
Epoch:23, w1:1.2880952634631702, w2:0.6838571222615248, bias:-0.4746563714368963, loss:0.6048547822772338
Epoch:24, w1:1.3051107743259742, w2:0.6808618833293014, bias:-0.48077298150380243, loss:0.6041791240519656
Epoch:25, w1:1.3221139896069845, w2:0.6780108562039149, bias:-0.48679326986147203, loss:0.6035085302709126
Epoch:26, w1:1.3390969335841574, w2:0.6752889090307138, bias:-0.4927368332846367, loss:0.6028427416381562
Epoch:27, w1:1.356053125263438, w2:0.6726833591525454, bias:-0.49861968276317203, loss:0.6021815629068819
Epoch:28, w1:1.3729773133260421, w2:0.6701835473755157, bias:-0.5044548783841586, loss:0.6015248428494415
Epoch:29, w1:1.3898652574423476, w2:0.6677804861708652, bias:-0.5102530532091296, loss:0.6008724606528864
Epoch:30, w1:1.4067135479854187, w2:0.6654665692202799, bias:-0.5160228452219537, loss:0.6002243166762635
Epoch:31, w1:1.42351945750019, w2:0.6632353317706492, bias:-0.5217712532510137, loss:0.5995803261668371
Epoch:32, w1:1.4402808184029094, w2:0.6610812530153767, bias:-0.5275039300896781, loss:0.5989404149826493
Epoch:33, w1:1.4569959223258953, w2:0.658999593198667, bias:-0.5332254237873099, loss:0.5983045166751372
Epoch:34, w1:1.4736634373098965, w2:0.6569862593822873, bias:-0.5389393761988883, loss:0.5976725704936393
Epoch:35, w1:1.490282339703033, w2:0.6550376948544813, bias:-0.544648686310049, loss:0.5970445200148714
Epoch:36, w1:1.5068518581715267, w2:0.6531507880281976, bias:-0.5503556445475507, loss:0.596420312196251
Epoch:37, w1:1.5233714276807901, w2:0.6513227973973159, bias:-0.5560620432007111, loss:0.595799896716878
Epoch:38, w1:1.539840651680997, w2:0.6495512897183726, bias:-0.5617692671809805, loss:0.5951832255139562
Epoch:39, w1:1.5562592710419292, w2:0.6478340890814017, bias:-0.567478368603682, loss:0.594570252452216
Epoch:40, w1:1.5726271385385526, w2:0.6461692349439407, bias:-0.5731901280619291, loss:0.5939609330840678
Epoch:41, w1:1.588944197900621, w2:0.6445549475414097, bias:-0.5789051049559077, loss:0.5933552244718447
Epoch:42, w1:1.6052104666143026, w2:0.6429895993670633, bias:-0.5846236788226703, loss:0.5927530850527324
Epoch:43, w1:1.621426021807804, w2:0.6414716916456821, bias:-0.5903460832670331, loss:0.5921544745332301
Epoch:44, w1:1.6375909886715547, w2:0.6399998349155704, bias:-0.5960724338103088, loss:0.5915593538042077
Epoch:45, w1:1.653705530961145, w2:0.6385727329903069, bias:-0.6018027507398699, loss:0.5909676848704918
Epoch:46, w1:1.6697698432115664, w2:0.6371891697008913, bias:-0.6075369778501342, loss:0.5903794307908431
Epoch:47, w1:1.6857841443574022, w2:0.6358479979253013, bias:-0.613274997807243, loss:0.5897945556255035
Epoch:48, w1:1.701748672507993, w2:0.6345481305000102, bias:-0.6190166447394482, loss:0.5892130243893768
Epoch:49, w1:1.7176636806713108, w2:0.6332885326800504, bias:-0.6247617145480917, loss:0.5886348030095084
Epoch:50, w1:1.733529433257035, w2:0.6320682158734605, bias:-0.6305099733459619, loss:0.5880598582859435
Epoch:51, w1:1.749346203219547, w2:0.6308862324246935, bias:-0.6362611643573645, loss:0.5874881578553106
Epoch:52, w1:1.765114269726393, w2:0.6297416712616426, bias:-0.642015013554692, loss:0.5869196701566792
Epoch:53, w1:1.7808339162581828, w2:0.6286336542538998, bias:-0.6477712342573156, loss:0.5863543643993574
Epoch:54, w1:1.7965054290626679, w2:0.627561333156963, bias:-0.6535295308783748, loss:0.585792210532392
Epoch:55, w1:1.8121290958995269, w2:0.6265238870393809, bias:-0.6592896019719668, loss:0.585233179215588
Epoch:56, w1:1.8277052050237126, w2:0.6255205201081449, bias:-0.6650511427060475, loss:0.5846772417919127
Epoch:57, w1:1.843234044364526, w2:0.6245504598626895, bias:-0.6708138468640122, loss:0.5841243702611733
Epoch:58, w1:1.858715900865226, w2:0.6236129555202405, bias:-0.6765774084595646, loss:0.5835745372548781
Epoch:59, w1:1.8741510599542681, w2:0.622707276665421, bias:-0.6823415230343887, loss:0.5830277160122108
Epoch:60, w1:1.8895398051244263, w2:0.6218327120853891, bias:-0.6881058886957416, loss:0.5824838803570515
Epoch:61, w1:1.9048824176002952, w2:0.6209885687586525, bias:-0.6938702069408932, loss:0.5819430046759891
Epoch:62, w1:1.92017917607815, w2:0.6201741709713547, bias:-0.699634183306963, loss:0.5814050638972774
Epoch:63, w1:1.9354303565250068, w2:0.6193888595394722, bias:-0.7053975278778283, loss:0.5808700334706856
Epoch:64, w1:1.9506362320260775, w2:0.6186319911191751, bias:-0.7111599556741177, loss:0.5803378893482043
Epoch:65, w1:1.9657970726717413, w2:0.6179029375907471, bias:-0.7169211869476638, loss:0.5798086079655687
Epoch:66, w1:1.98091314547675, w2:0.6172010855040322, bias:-0.7226809473979643, loss:0.5792821662245574
Epoch:67, w1:1.995984714325677, w2:0.6165258355755011, bias:-0.7284389683250697, loss:0.5787585414760404
Epoch:68, w1:2.011012039939704, w2:0.6158766022287703, bias:-0.7341949867307338, loss:0.5782377115037348
Epoch:69, w1:2.0259953798607047, w2:0.6152528131718392, bias:-0.7399487453775457, loss:0.5777196545086449
Epoch:70, w1:2.040934988449324, w2:0.6146539090054908, bias:-0.7456999928140228, loss:0.577204349094153
Epoch:71, w1:2.055831116894333, w2:0.6140793428582669, bias:-0.7514484833722109, loss:0.5766917742517326
Epoch:72, w1:2.0706840132310274, w2:0.6135285800442278, bias:-0.7571939771431664, loss:0.5761819093472604
Epoch:73, w1:2.0854939223668545, w2:0.6130010977403592, bias:-0.7629362399347244, loss:0.5756747341078993
Epoch:74, w1:2.100261086112758, w2:0.6124963846810303, bias:-0.7686750432151684, loss:0.5751702286095264
Epoch:75, w1:2.1149857432190236, w2:0.6120139408673478, bias:-0.7744101640457616, loss:0.5746683732646869
Epoch:76, w1:2.1296681294146156, w2:0.6115532772896162, bias:-0.7801413850045639, loss:0.5741691488110475
Epoch:77, w1:2.1443084774491856, w2:0.6111139156614152, bias:-0.7858684941035217, loss:0.5736725363003305
Epoch:78, w1:2.15890701713708, w2:0.6106953881640519, bias:-0.7915912847004521, loss:0.5731785170877063
Epoch:79, w1:2.1734639754027962, w2:0.610297237200348, bias:-0.7973095554072482, loss:0.5726870728216269
Epoch:80, w1:2.187979576327446, w2:0.6099190151568912, bias:-0.8030231099953868, loss:0.572198185434078
Epoch:81, w1:2.2024540411958538, w2:0.6095602841740171, bias:-0.808731757299621, loss:0.5717118371312375
Epoch:82, w1:2.2168875885440005, w2:0.6092206159229021, bias:-0.8144353111205729, loss:0.5712280103845162
Epoch:83, w1:2.231280434206573, w2:0.6088995913892419, bias:-0.8201335901268091, loss:0.570746687921971
Epoch:84, w1:2.2456327913644185, w2:0.6085968006630673, bias:-0.8258264177568682, loss:0.5702678527200695
Epoch:85, w1:2.2599448705917586, w2:0.6083118427343136, bias:-0.83151362212162, loss:0.5697914879957938
Epoch:86, w1:2.274216879903029, w2:0.6080443252938127, bias:-0.8371950359072613, loss:0.5693175771990695
Epoch:87, w1:2.28844902479925, w2:0.6077938645394205, bias:-0.8428704962791888, loss:0.5688461040055036
Epoch:88, w1:2.30264150831385, w2:0.6075600849870302, bias:-0.8485398447869447, loss:0.5683770523094195
Epoch:89, w1:2.316794531057877, w2:0.607342619286249, bias:-0.8542029272703846, loss:0.5679104062171778
Epoch:90, w1:2.3309082912645533, w2:0.6071411080405451, bias:-0.8598595937671849, loss:0.5674461500407687
Epoch:91, w1:2.3449829848331394, w2:0.6069551996316898, bias:-0.86550969842178, loss:0.5669842682916635
Epoch:92, w1:2.3590188053720738, w2:0.6067845500483374, bias:-0.8711530993957975, loss:0.5665247456749185
Epoch:93, w1:2.373015944241379, w2:0.6066288227186024, bias:-0.8767896587800372, loss:0.5660675670835165
Epoch:94, w1:2.386974590594313, w2:0.6064876883465028, bias:-0.8824192425080308, loss:0.5656127175929359
Epoch:95, w1:2.400894931418264, w2:0.6063608247521508, bias:-0.8880417202712013, loss:0.5651601824559409
Epoch:96, w1:2.4147771515748837, w2:0.6062479167155812, bias:-0.8936569654356342, loss:0.5647099470975807
Epoch:97, w1:2.4286214338394565, w2:0.6061486558241135, bias:-0.899264854960464, loss:0.5642619971103882
Epoch:98, w1:2.442427958939513, w2:0.606062740323152, bias:-0.9048652693178719, loss:0.5638163182497724
Epoch:99, w1:2.456196905592686, w2:0.6059898749703329, bias:-0.9104580924146866, loss:0.5633728964295956
Epoch:100, w1:2.469928450543822, w2:0.6059297708929318, bias:-0.9160432115155751, loss:0.5629317177179232
Epoch:101, w1:2.4836227686013514, w2:0.6058821454484511, bias:-0.9216205171678082, loss:0.5624927683329463
Epoch:102, w1:2.4972800326729296, w2:0.6058467220883077, bias:-0.9271899031275801, loss:0.5620560346390636
Epoch:103, w1:2.5109004138003574, w2:0.6058232302245465, bias:-0.9327512662878625, loss:0.5616215031431182
Epoch:104, w1:2.5244840811937936, w2:0.6058114050995085, bias:-0.9383045066077705, loss:0.561189160490783
Epoch:105, w1:2.538031202265267, w2:0.6058109876583826, bias:-0.9438495270434162, loss:0.560758993463087
Epoch:106, w1:2.551541942661504, w2:0.6058217244245757, bias:-0.9493862334802252, loss:0.5603309889730781
Epoch:107, w1:2.56501646629608, w2:0.6058433673778353, bias:-0.9549145346666914, loss:0.5599051340626159
Epoch:108, w1:2.5784549353809094, w2:0.6058756738350617, bias:-0.9604343421495434, loss:0.5594814158992881
Epoch:109, w1:2.5918575104570842, w2:0.6059184063337493, bias:-0.9659455702102974, loss:0.5590598217734468
Epoch:110, w1:2.6052243504250736, w2:0.605971332517997, bias:-0.9714481358031697, loss:0.5586403390953593
Epoch:111, w1:2.6185556125743, w2:0.6060342250270309, bias:-0.9769419584943234, loss:0.558222955392466
Epoch:112, w1:2.631851452612096, w2:0.6061068613861819, bias:-0.9824269604024229, loss:0.5578076583067462
Epoch:113, w1:2.645112024692065, w2:0.6061890239002645, bias:-0.9879030661404701, loss:0.5573944355921815
Epoch:114, w1:2.6583374814418463, w2:0.606280499549303, bias:-0.993370202758897, loss:0.5569832751123156
Epoch:115, w1:2.671527973990306, w2:0.6063810798865519, bias:-0.9988282996898897, loss:0.5565741648379074
Epoch:116, w1:2.684683651994157, w2:0.6064905609387626, bias:-1.004277288692918, loss:0.5561670928446703
Epoch:117, w1:2.697804663664027, w2:0.6066087431086429, bias:-1.0097171038014463, loss:0.5557620473110961
Epoch:118, w1:2.710891155789981, w2:0.6067354310794633, bias:-1.0151476812708007, loss:0.5553590165163611
Epoch:119, w1:2.7239432737665106, w2:0.6068704337217623, bias:-1.0205689595271705, loss:0.5549579888383077
Epoch:120, w1:2.7369611616170024, w2:0.6070135640021044, bias:-1.0259808791177178, loss:0.5545589527515004
Epoch:121, w1:2.7499449620176937, w2:0.6071646388938436, bias:-1.0313833826617735, loss:0.5541618968253538
Epoch:122, w1:2.76289481632113, w2:0.6073234792898522, bias:-1.0367764148030967, loss:0.5537668097223267
Epoch:123, w1:2.7758108645791295, w2:0.6074899099171669, bias:-1.0421599221631754, loss:0.5533736801961834
Epoch:124, w1:2.7886932455652707, w2:0.6076637592535139, bias:-1.0475338532955458, loss:0.5529824970903151
Epoch:125, w1:2.8015420967969074, w2:0.607844859445669, bias:-1.0528981586411095, loss:0.5525932493361221
Epoch:126, w1:2.8143575545567265, w2:0.6080330462296135, bias:-1.0582527904844266, loss:0.552205925951454
Epoch:127, w1:2.827139753913853, w2:0.6082281588524461, bias:-1.0635977029109653, loss:0.551820516039103
Epoch:128, w1:2.8398888287445154, w2:0.6084300399960116, bias:-1.0689328517652867, loss:0.5514370087853504
Epoch:129, w1:2.8526049117522803, w2:0.6086385357022098, bias:-1.0742581946101435, loss:0.551055393458564
Epoch:130, w1:2.8652881344878627, w2:0.6088534952999458, bias:-1.0795736906864768, loss:0.550675659407842
Epoch:131, w1:2.877938627368525, w2:0.6090747713336875, bias:-1.084879300874289, loss:0.5502977960617058
Epoch:132, w1:2.8905565196970695, w2:0.6093022194935929, bias:-1.090174987654374, loss:0.5499217929268336
Epoch:133, w1:2.9031419396804368, w2:0.6095356985471746, bias:-1.0954607150708882, loss:0.5495476395868397
Epoch:134, w1:2.9156950144479143, w2:0.6097750702724658, bias:-1.1007364486947417, loss:0.5491753257010914
Epoch:135, w1:2.9282158700689678, w2:0.610020199392656, bias:-1.1060021555877961, loss:0.5488048410035673
Epoch:136, w1:2.940704631570699, w2:0.6102709535121631, bias:-1.1112578042678465, loss:0.5484361753017519
Epoch:137, w1:2.9531614229549428, w2:0.6105272030541111, bias:-1.1165033646743747, loss:0.5480693184755655
Epoch:138, w1:2.9655863672150065, w2:0.6107888211991817, bias:-1.1217388081350563, loss:0.5477042604763288
Epoch:139, w1:2.9779795863520624, w2:0.6110556838258094, bias:-1.126964107333004, loss:0.5473409913257608
Epoch:140, w1:2.990341201391199, w2:0.6113276694516916, bias:-1.1321792362747316, loss:0.5469795011150076
Epoch:141, w1:3.002671332397141, w2:0.6116046591765828, bias:-1.137384170258826, loss:0.5466197800037016
Epoch:142, w1:3.014970098489638, w2:0.6118865366263468, bias:-1.142578885845308, loss:0.5462618182190492
Epoch:143, w1:3.0272376178585434, w2:0.6121731878982372, bias:-1.1477633608256685, loss:0.5459056060549479
Epoch:144, w1:3.03947400777857, w2:0.6124645015073797, bias:-1.1529375741935666, loss:0.5455511338711271
Epoch:145, w1:3.0516793846237484, w2:0.6127603683344313, bias:-1.1581015061161746, loss:0.5451983920923182
Epoch:146, w1:3.063853863881584, w2:0.6130606815743865, bias:-1.1632551379061544, loss:0.5448473712074455
Epoch:147, w1:3.0759975601669196, w2:0.6133653366865107, bias:-1.1683984519942547, loss:0.5444980617688431
Epoch:148, w1:3.0881105872355143, w2:0.61367423134537, bias:-1.1735314319025125, loss:0.5441504543914931
Epoch:149, w1:3.1001930579973416, w2:0.6139872653929379, bias:-1.1786540622180477, loss:0.543804539752286
Epoch:150, w1:3.1122450845296132, w2:0.6143043407917526, bias:-1.1837663285674376, loss:0.5434603085893024
Epoch:151, w1:3.124266778089535, w2:0.6146253615791026, bias:-1.1888682175916574, loss:0.5431177517011123
Epoch:152, w1:3.1362582491268003, w2:0.6149502338222177, bias:-1.1939597169215774, loss:0.5427768599460967
Epoch:153, w1:3.1482196072958275, w2:0.6152788655744427, bias:-1.1990408151540015, loss:0.5424376242417848
Epoch:154, w1:3.1601509614677465, w2:0.6156111668323733, bias:-1.2041115018282362, loss:0.5421000355642106
Epoch:155, w1:3.172052419742138, w2:0.6159470494939316, bias:-1.2091717674031812, loss:0.5417640849472858
Epoch:156, w1:3.1839240894585337, w2:0.6162864273173618, bias:-1.2142216032349262, loss:0.5414297634821882
Epoch:157, w1:3.1957660772076832, w2:0.616629215881124, bias:-1.219261001554845, loss:0.5410970623167669
Epoch:158, w1:3.207578488842587, w2:0.6169753325446679, bias:-1.2242899554481772, loss:0.5407659726549621
Epoch:159, w1:3.2193614294893074, w2:0.6173246964100669, bias:-1.2293084588330838, loss:0.5404364857562383
Epoch:160, w1:3.231115003557557, w2:0.6176772282844922, bias:-1.2343165064401693, loss:0.540108592935033
Epoch:161, w1:3.242839314751075, w2:0.6180328506435094, bias:-1.2393140937924587, loss:0.5397822855602173
Epoch:162, w1:3.254534466077791, w2:0.6183914875951794, bias:-1.2443012171858197, loss:0.5394575550545702
Epoch:163, w1:3.2662005598597807, w2:0.6187530648449455, bias:-1.24927787366982, loss:0.5391343928942633
Epoch:164, w1:3.277837697743024, w2:0.6191175096612901, bias:-1.2542440610290118, loss:0.5388127906083611
Epoch:165, w1:3.289445980706962, w2:0.6194847508421424, bias:-1.2591997777646313, loss:0.5384927397783275
Epoch:166, w1:3.301025509073864, w2:0.619854718682022, bias:-1.264145023076708, loss:0.5381742320375478
Epoch:167, w1:3.312576382518004, w2:0.6202273449399023, bias:-1.2690797968465704, loss:0.5378572590708587
Epoch:168, w1:3.3240987000746527, w2:0.6206025628077756, bias:-1.2740040996197441, loss:0.5375418126140888
Epoch:169, w1:3.3355925601488896, w2:0.6209803068799076, bias:-1.2789179325892295, loss:0.5372278844536086
Epoch:170, w1:3.3470580605242373, w2:0.6213605131227634, bias:-1.2838212975791532, loss:0.536915466425891
Epoch:171, w1:3.358495298371124, w2:0.6217431188455917, bias:-1.2887141970287852, loss:0.5366045504170793
Epoch:172, w1:3.3699043702551745, w2:0.6221280626716518, bias:-1.2935966339769118, loss:0.5362951283625649
Epoch:173, w1:3.3812853721453404, w2:0.6225152845100694, bias:-1.298468612046559, loss:0.5359871922465721
Epoch:174, w1:3.3926383994218634, w2:0.6229047255283084, bias:-1.3033301354300564, loss:0.5356807341017529
Epoch:175, w1:3.403963546884082, w2:0.6232963281252433, bias:-1.3081812088744358, loss:0.5353757460087871
Epoch:176, w1:3.415260908758085, w2:0.6236900359048196, bias:-1.3130218376671565, loss:0.5350722200959926
Epoch:177, w1:3.4265305787042117, w2:0.6240857936502907, bias:-1.3178520276221497, loss:0.5347701485389392
Epoch:178, w1:3.4377726498244034, w2:0.6244835472990157, bias:-1.3226717850661762, loss:0.5344695235600743
Epoch:179, w1:3.4489872146694114, w2:0.6248832439178086, bias:-1.3274811168254896, loss:0.5341703374283489
Epoch:180, w1:3.4601743652458627, w2:0.6252848316788245, bias:-1.3322800302127977, loss:0.533872582458857
Epoch:181, w1:3.4713341930231865, w2:0.6256882598359729, bias:-1.3370685330145182, loss:0.5335762510124759
Epoch:182, w1:3.482466788940404, w2:0.6260934787018441, bias:-1.3418466334783188, loss:0.533281335495514
Epoch:183, w1:3.493572243412788, w2:0.6265004396251397, bias:-1.3466143403009374, loss:0.5329878283593665
Epoch:184, w1:3.50465064633839, w2:0.6269090949685953, bias:-1.3513716626162766, loss:0.5326957221001725
Epoch:185, w1:3.5157020871044424, w2:0.6273193980873831, bias:-1.3561186099837659, loss:0.5324050092584822
Epoch:186, w1:3.526726654593633, w2:0.6277313033079868, bias:-1.360855192376984, loss:0.5321156824189253
Epoch:187, w1:3.5377244371902634, w2:0.6281447659075344, bias:-1.3655814201725396, loss:0.5318277342098869
Epoch:188, w1:3.5486955227862818, w2:0.6285597420935836, bias:-1.3702973041392001, loss:0.5315411573031879

(np.float64(7.762790740073865),
 np.float64(0.8757995704927221),
 np.float64(-3.2050626291525384))