In [3]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\jacob\appdata\roaming\python\python313\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\jacob\appdata\roaming\python\python313\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jacob\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jacob\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jacob\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\jacob\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
import pandas as pd
df=pd.read_csv(r"C:\Users\jacob\Downloads\loan_data_set_lyst1728376986423 (1).csv")
df.isnull().sum()
df.ffill(inplace=True)
df.bfill(inplace=True)
df1=pd.get_dummies(df,columns=["Gender","Married","Dependents","Education","Self_Employed","Property_Area","Loan_Status"])
df1.dtypes
df1.drop("Gender_Female",axis=1,inplace=True)
df1.drop("Married_No",axis=1,inplace=True)
df1.drop("Education_Graduate",axis=1,inplace=True)
df1.drop("Self_Employed_No",axis=1,inplace=True)
df1.drop("Property_Area_Rural",axis=1,inplace=True)
df1.drop("Loan_Status_N",axis=1,inplace=True)
df1.drop("Dependents_3+",axis=1,inplace=True)
x=df1.iloc[:,2:15]
y=df1.iloc[:,-1]

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [13]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\jacob\appdata\roaming\python\python313\site-packages (from scikit-learn) (2.3.2)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.16.3-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp313-cp313-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.0 MB 293.9 kB/s eta 0:00:26
   -- ------------------------------------- 0.5/8.0 MB 293.9 kB/s eta 0:00:26
   -- ------------------------------------- 0.5/8.0 MB 293.9 kB/s eta 0:00:26
   -- ------------------------------------- 0.5/8.0 MB 293.9 kB/s eta 0:00:26
   -- ------------------------------------- 0.5/8.0 MB 293.9 kB/s eta 0:00:26
   --- ------------------------------------ 0.8/8.0 MB 254.6 kB/s eta 0:00:29
   --- ------------------------------------ 0.8/8.0 MB 254.6 kB/s eta 0:00:29
   --- ------------------------------------ 0.8/8.0 MB 254.6 kB/s eta 0:00:29
   ----- ---------------------------------- 1.0/8.0 MB 291.7 kB/s eta 0:00:24
   ----- ---------------------------------- 1.0/8.0 MB 291.7 kB/s eta 0:00:24
   ----- ---------------------------------- 1.0/8.0 MB 291.7 kB/s eta 0:00:24
   ------ --------------------------------- 1.3/8.0 MB 328.0 kB/s eta 0:00:21
   ------ --------------------------------- 1.3/8.0 MB 328.0 kB/s eta 0:00:21
   ------ --------------------------------- 1.3/8.0 MB 328.0 kB/s eta 0:00:21
   ------ --------------------------------- 1.3/8.0 MB 328.0 kB/s eta 0:00:21
   ------ --------------------------------- 1.3/8.0 MB 328.0 kB/s eta 0:00:21
   ------- -------------------------------- 1.6/8.0 MB 297.5 kB/s eta 0:00:22
   ------- -------------------------------- 1.6/8.0 MB 297.5 kB/s eta 0:00:22
   ------- -------------------------------- 1.6/8.0 MB 297.5 kB/s eta 0:00:22
   ------- -------------------------------- 1.6/8.0 MB 297.5 kB/s eta 0:00:22
   ------- -------------------------------- 1.6/8.0 MB 297.5 kB/s eta 0:00:22
   ------- -------------------------------- 1.6/8.0 MB 297.5 kB/s eta 0:00:22
   --------- ------------------------------ 1.8/8.0 MB 277.5 kB/s eta 0:00:23
   --------- ------------------------------ 1.8/8.0 MB 277.5 kB/s eta 0:00:23
   --------- ------------------------------ 1.8/8.0 MB 277.5 kB/s eta 0:00:23
   --------- ------------------------------ 1.8/8.0 MB 277.5 kB/s eta 0:00:23
   ---------- ----------------------------- 2.1/8.0 MB 287.3 kB/s eta 0:00:21
   ---------- ----------------------------- 2.1/8.0 MB 287.3 kB/s eta 0:00:21
   ---------- ----------------------------- 2.1/8.0 MB 287.3 kB/s eta 0:00:21
   ---------- ----------------------------- 2.1/8.0 MB 287.3 kB/s eta 0:00:21
   ---------- ----------------------------- 2.1/8.0 MB 287.3 kB/s eta 0:00:21
   ---------- ----------------------------- 2.1/8.0 MB 287.3 kB/s eta 0:00:21
   ---------- ----------------------------- 2.1/8.0 MB 287.3 kB/s eta 0:00:21
   ----------- ---------------------------- 2.4/8.0 MB 269.5 kB/s eta 0:00:21
   ----------- ---------------------------- 2.4/8.0 MB 269.5 kB/s eta 0:00:21
   ----------- ---------------------------- 2.4/8.0 MB 269.5 kB/s eta 0:00:21
   ----------- ---------------------------- 2.4/8.0 MB 269.5 kB/s eta 0:00:21
   ----------- ---------------------------- 2.4/8.0 MB 269.5 kB/s eta 0:00:21
   ----------- ---------------------------- 2.4/8.0 MB 269.5 kB/s eta 0:00:21
   ----------- ---------------------------- 2.4/8.0 MB 269.5 kB/s eta 0:00:21
   ----------- ---------------------------- 2.4/8.0 MB 269.5 kB/s eta 0:00:21
   ----------- ---------------------------- 2.4/8.0 MB 269.5 kB/s eta 0:00:21
   ------------- -------------------------- 2.6/8.0 MB 245.1 kB/s eta 0:00:22
   ------------- -------------------------- 2.6/8.0 MB 245.1 kB/s eta 0:00:22
   ------------- -------------------------- 2.6/8.0 MB 245.1 kB/s eta 0:00:22
   ------------- -------------------------- 2.6/8.0 MB 245.1 kB/s eta 0:00:22
   ------------- -------------------------- 2.6/8.0 MB 245.1 kB/s eta 0:00:22
   ------------- -------------------------- 2.6/8.0 MB 245.1 kB/s eta 0:00:22
   ------------- -------------------------- 2.6/8.0 MB 245.1 kB/s eta 0:00:22
   ------------- -------------------------- 2.6/8.0 MB 245.1 kB/s eta 0:00:22
   -------------- ------------------------- 2.9/8.0 MB 228.2 kB/s eta 0:00:23
   -------------- ------------------------- 2.9/8.0 MB 228.2 kB/s eta 0:00:23
   -------------- ------------------------- 2.9/8.0 MB 228.2 kB/s eta 0:00:23
   -------------- ------------------------- 2.9/8.0 MB 228.2 kB/s eta 0:00:23
   -------------- ------------------------- 2.9/8.0 MB 228.2 kB/s eta 0:00:23
   -------------- ------------------------- 2.9/8.0 MB 228.2 kB/s eta 0:00:23
   -------------- ------------------------- 2.9/8.0 MB 228.2 kB/s eta 0:00:23
   -------------- ------------------------- 2.9/8.0 MB 228.2 kB/s eta 0:00:23
   -------------- ------------------------- 2.9/8.0 MB 228.2 kB/s eta 0:00:23
   -------------- ------------------------- 2.9/8.0 MB 228.2 kB/s eta 0:00:23
   -------------- ------------------------- 2.9/8.0 MB 228.2 kB/s eta 0:00:23
   -------------- ------------------------- 2.9/8.0 MB 228.2 kB/s eta 0:00:23
   -------------- ------------------------- 2.9/8.0 MB 228.2 kB/s eta 0:00:23
   --------------- ------------------------ 3.1/8.0 MB 202.5 kB/s eta 0:00:24
   --------------- ------------------------ 3.1/8.0 MB 202.5 kB/s eta 0:00:24
   --------------- ------------------------ 3.1/8.0 MB 202.5 kB/s eta 0:00:24
   --------------- ------------------------ 3.1/8.0 MB 202.5 kB/s eta 0:00:24
   ----------------- ---------------------- 3.4/8.0 MB 209.7 kB/s eta 0:00:22
   ----------------- ---------------------- 3.4/8.0 MB 209.7 kB/s eta 0:00:22
   ------------------ --------------------- 3.7/8.0 MB 222.1 kB/s eta 0:00:20
   ------------------ --------------------- 3.7/8.0 MB 222.1 kB/s eta 0:00:20
   ------------------ --------------------- 3.7/8.0 MB 222.1 kB/s eta 0:00:20
   ------------------ --------------------- 3.7/8.0 MB 222.1 kB/s eta 0:00:20
   ------------------ --------------------- 3.7/8.0 MB 222.1 kB/s eta 0:00:20
   ------------------- -------------------- 3.9/8.0 MB 223.0 kB/s eta 0:00:19
   ------------------- -------------------- 3.9/8.0 MB 223.0 kB/s eta 0:00:19
   ------------------- -------------------- 3.9/8.0 MB 223.0 kB/s eta 0:00:19
   -------------------- ------------------- 4.2/8.0 MB 230.1 kB/s eta 0:00:17
   -------------------- ------------------- 4.2/8.0 MB 230.1 kB/s eta 0:00:17
   -------------------- ------------------- 4.2/8.0 MB 230.1 kB/s eta 0:00:17
   ---------------------- ----------------- 4.5/8.0 MB 238.0 kB/s eta 0:00:15
   ---------------------- ----------------- 4.5/8.0 MB 238.0 kB/s eta 0:00:15
   ---------------------- ----------------- 4.5/8.0 MB 238.0 kB/s eta 0:00:15
   ----------------------- ---------------- 4.7/8.0 MB 244.3 kB/s eta 0:00:14
   ----------------------- ---------------- 4.7/8.0 MB 244.3 kB/s eta 0:00:14
   ----------------------- ---------------- 4.7/8.0 MB 244.3 kB/s eta 0:00:14
   ------------------------ --------------- 5.0/8.0 MB 249.0 kB/s eta 0:00:13
   ------------------------ --------------- 5.0/8.0 MB 249.0 kB/s eta 0:00:13
   ------------------------ --------------- 5.0/8.0 MB 249.0 kB/s eta 0:00:13
   ------------------------ --------------- 5.0/8.0 MB 249.0 kB/s eta 0:00:13
   ------------------------ --------------- 5.0/8.0 MB 249.0 kB/s eta 0:00:13
   ------------------------ --------------- 5.0/8.0 MB 249.0 kB/s eta 0:00:13
   ------------------------ --------------- 5.0/8.0 MB 249.0 kB/s eta 0:00:13
   -------------------------- ------------- 5.2/8.0 MB 245.6 kB/s eta 0:00:12
   -------------------------- ------------- 5.2/8.0 MB 245.6 kB/s eta 0:00:12
   -------------------------- ------------- 5.2/8.0 MB 245.6 kB/s eta 0:00:12
   -------------------------- ------------- 5.2/8.0 MB 245.6 kB/s eta 0:00:12
   -------------------------- ------------- 5.2/8.0 MB 245.6 kB/s eta 0:00:12
   -------------------------- ------------- 5.2/8.0 MB 245.6 kB/s eta 0:00:12
   -------------------------- ------------- 5.2/8.0 MB 245.6 kB/s eta 0:00:12
   -------------------------- ------------- 5.2/8.0 MB 245.6 kB/s eta 0:00:12
   -------------------------- ------------- 5.2/8.0 MB 245.6 kB/s eta 0:00:12
   -------------------------- ------------- 5.2/8.0 MB 245.6 kB/s eta 0:00:12
   --------------------------- ------------ 5.5/8.0 MB 232.4 kB/s eta 0:00:11
   --------------------------- ------------ 5.5/8.0 MB 232.4 kB/s eta 0:00:11
   --------------------------- ------------ 5.5/8.0 MB 232.4 kB/s eta 0:00:11
   ---------------------------- ----------- 5.8/8.0 MB 238.8 kB/s eta 0:00:10
   ---------------------------- ----------- 5.8/8.0 MB 238.8 kB/s eta 0:00:10
   ------------------------------ --------- 6.0/8.0 MB 244.5 kB/s eta 0:00:09
   ------------------------------ --------- 6.0/8.0 MB 244.5 kB/s eta 0:00:09
   ------------------------------- -------- 6.3/8.0 MB 251.0 kB/s eta 0:00:07
   ------------------------------- -------- 6.3/8.0 MB 251.0 kB/s eta 0:00:07
   -------------------------------- ------- 6.6/8.0 MB 257.7 kB/s eta 0:00:06
   -------------------------------- ------- 6.6/8.0 MB 257.7 kB/s eta 0:00:06
   ---------------------------------- ----- 6.8/8.0 MB 263.8 kB/s eta 0:00:05
   ---------------------------------- ----- 6.8/8.0 MB 263.8 kB/s eta 0:00:05
   ----------------------------------- ---- 7.1/8.0 MB 270.1 kB/s eta 0:00:04
   ----------------------------------- ---- 7.1/8.0 MB 270.1 kB/s eta 0:00:04
   ------------------------------------ --- 7.3/8.0 MB 276.3 kB/s eta 0:00:03
   ------------------------------------ --- 7.3/8.0 MB 276.3 kB/s eta 0:00:03
   -------------------------------------- - 7.6/8.0 MB 282.4 kB/s eta 0:00:02
   ---------------------------------------  7.9/8.0 MB 288.8 kB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 291.8 kB/s eta 0:00:00
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.16.3-cp313-cp313-win_amd64.whl (38.5 MB)
   ---------------------------------------- 0.0/38.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/38.5 MB ? eta -:--:--
    --------------------------------------- 0.5/38.5 MB 1.0 MB/s eta 0:00:38
    --------------------------------------- 0.8/38.5 MB 1.2 MB/s eta 0:00:32
   - -------------------------------------- 1.0/38.5 MB 1.1 MB/s eta 0:00:34
   - -------------------------------------- 1.3/38.5 MB 1.2 MB/s eta 0:00:31
   - -------------------------------------- 1.6/38.5 MB 1.2 MB/s eta 0:00:31
   - -------------------------------------- 1.8/38.5 MB 1.2 MB/s eta 0:00:32
   -- ------------------------------------- 2.1/38.5 MB 1.2 MB/s eta 0:00:30
   -- ------------------------------------- 2.6/38.5 MB 1.3 MB/s eta 0:00:29
   -- ------------------------------------- 2.9/38.5 MB 1.3 MB/s eta 0:00:28
   --- ------------------------------------ 3.1/38.5 MB 1.3 MB/s eta 0:00:28
   --- ------------------------------------ 3.4/38.5 MB 1.3 MB/s eta 0:00:28
   --- ------------------------------------ 3.4/38.5 MB 1.3 MB/s eta 0:00:28
   --- ------------------------------------ 3.4/38.5 MB 1.3 MB/s eta 0:00:28
   --- ------------------------------------ 3.4/38.5 MB 1.3 MB/s eta 0:00:28
   --- ------------------------------------ 3.7/38.5 MB 1.1 MB/s eta 0:00:33
   --- ------------------------------------ 3.7/38.5 MB 1.1 MB/s eta 0:00:33
   --- ------------------------------------ 3.7/38.5 MB 1.1 MB/s eta 0:00:33
   --- ------------------------------------ 3.7/38.5 MB 1.1 MB/s eta 0:00:33
   --- ------------------------------------ 3.7/38.5 MB 1.1 MB/s eta 0:00:33
   --- ------------------------------------ 3.7/38.5 MB 1.1 MB/s eta 0:00:33
   --- ------------------------------------ 3.7/38.5 MB 1.1 MB/s eta 0:00:33
   ---- ----------------------------------- 3.9/38.5 MB 769.8 kB/s eta 0:00:45
   ---- ----------------------------------- 3.9/38.5 MB 769.8 kB/s eta 0:00:45
   ---- ----------------------------------- 3.9/38.5 MB 769.8 kB/s eta 0:00:45
   ---- ----------------------------------- 3.9/38.5 MB 769.8 kB/s eta 0:00:45
   ---- ----------------------------------- 4.2/38.5 MB 706.3 kB/s eta 0:00:49
   ---- ----------------------------------- 4.2/38.5 MB 706.3 kB/s eta 0:00:49
   ---- ----------------------------------- 4.2/38.5 MB 706.3 kB/s eta 0:00:49
   ---- ----------------------------------- 4.2/38.5 MB 706.3 kB/s eta 0:00:49
   ---- ----------------------------------- 4.2/38.5 MB 706.3 kB/s eta 0:00:49
   ---- ----------------------------------- 4.2/38.5 MB 706.3 kB/s eta 0:00:49
   ---- ----------------------------------- 4.2/38.5 MB 706.3 kB/s eta 0:00:49
   ---- ----------------------------------- 4.2/38.5 MB 706.3 kB/s eta 0:00:49
   ---- ----------------------------------- 4.2/38.5 MB 706.3 kB/s eta 0:00:49
   ---- ----------------------------------- 4.5/38.5 MB 567.1 kB/s eta 0:01:01
   ---- ----------------------------------- 4.5/38.5 MB 567.1 kB/s eta 0:01:01
   ---- ----------------------------------- 4.5/38.5 MB 567.1 kB/s eta 0:01:01
   ---- ----------------------------------- 4.5/38.5 MB 567.1 kB/s eta 0:01:01
   ---- ----------------------------------- 4.7/38.5 MB 533.3 kB/s eta 0:01:04
   ---- ----------------------------------- 4.7/38.5 MB 533.3 kB/s eta 0:01:04
   ---- ----------------------------------- 4.7/38.5 MB 533.3 kB/s eta 0:01:04
   ----- ---------------------------------- 5.0/38.5 MB 529.4 kB/s eta 0:01:04
   ----- ---------------------------------- 5.2/38.5 MB 542.8 kB/s eta 0:01:02
   ----- ---------------------------------- 5.5/38.5 MB 560.6 kB/s eta 0:00:59
   ----- ---------------------------------- 5.8/38.5 MB 574.6 kB/s eta 0:00:58
   ----- ---------------------------------- 5.8/38.5 MB 574.6 kB/s eta 0:00:58
   ------ --------------------------------- 6.6/38.5 MB 629.2 kB/s eta 0:00:51
   ------ --------------------------------- 6.6/38.5 MB 629.2 kB/s eta 0:00:51
   ------- -------------------------------- 7.3/38.5 MB 683.2 kB/s eta 0:00:46
   -------- ------------------------------- 7.9/38.5 MB 715.9 kB/s eta 0:00:43
   -------- ------------------------------- 8.4/38.5 MB 751.4 kB/s eta 0:00:41
   --------- ------------------------------ 8.9/38.5 MB 780.4 kB/s eta 0:00:38
   --------- ------------------------------ 8.9/38.5 MB 780.4 kB/s eta 0:00:38
   --------- ------------------------------ 9.2/38.5 MB 787.9 kB/s eta 0:00:38
   --------- ------------------------------ 9.2/38.5 MB 787.9 kB/s eta 0:00:38
   --------- ------------------------------ 9.4/38.5 MB 779.7 kB/s eta 0:00:38
   --------- ------------------------------ 9.4/38.5 MB 779.7 kB/s eta 0:00:38
   --------- ------------------------------ 9.4/38.5 MB 779.7 kB/s eta 0:00:38
   ---------- ----------------------------- 9.7/38.5 MB 753.5 kB/s eta 0:00:39
   ---------- ----------------------------- 9.7/38.5 MB 753.5 kB/s eta 0:00:39
   ---------- ----------------------------- 9.7/38.5 MB 753.5 kB/s eta 0:00:39
   ---------- ----------------------------- 10.0/38.5 MB 739.8 kB/s eta 0:00:39
   ---------- ----------------------------- 10.2/38.5 MB 748.5 kB/s eta 0:00:38
   ---------- ----------------------------- 10.2/38.5 MB 748.5 kB/s eta 0:00:38
   ---------- ----------------------------- 10.5/38.5 MB 746.1 kB/s eta 0:00:38
   ---------- ----------------------------- 10.5/38.5 MB 746.1 kB/s eta 0:00:38
   ----------- ---------------------------- 10.7/38.5 MB 739.4 kB/s eta 0:00:38
   ----------- ---------------------------- 10.7/38.5 MB 739.4 kB/s eta 0:00:38
   ----------- ---------------------------- 10.7/38.5 MB 739.4 kB/s eta 0:00:38
   ----------- ---------------------------- 10.7/38.5 MB 739.4 kB/s eta 0:00:38
   ----------- ---------------------------- 10.7/38.5 MB 739.4 kB/s eta 0:00:38
   ----------- ---------------------------- 11.0/38.5 MB 708.9 kB/s eta 0:00:39
   ----------- ---------------------------- 11.0/38.5 MB 708.9 kB/s eta 0:00:39
   ----------- ---------------------------- 11.3/38.5 MB 706.6 kB/s eta 0:00:39
   ----------- ---------------------------- 11.3/38.5 MB 706.6 kB/s eta 0:00:39
   ----------- ---------------------------- 11.5/38.5 MB 704.5 kB/s eta 0:00:39
   ----------- ---------------------------- 11.5/38.5 MB 704.5 kB/s eta 0:00:39
   ------------ --------------------------- 11.8/38.5 MB 699.9 kB/s eta 0:00:39
   ------------ --------------------------- 12.1/38.5 MB 701.7 kB/s eta 0:00:38
   ------------ --------------------------- 12.1/38.5 MB 701.7 kB/s eta 0:00:38
   ------------ --------------------------- 12.3/38.5 MB 705.7 kB/s eta 0:00:38
   ------------ --------------------------- 12.3/38.5 MB 705.7 kB/s eta 0:00:38
   ------------- -------------------------- 12.6/38.5 MB 703.8 kB/s eta 0:00:37
   ------------- -------------------------- 12.6/38.5 MB 703.8 kB/s eta 0:00:37
   ------------- -------------------------- 12.8/38.5 MB 700.8 kB/s eta 0:00:37
   ------------- -------------------------- 12.8/38.5 MB 700.8 kB/s eta 0:00:37
   ------------- -------------------------- 13.1/38.5 MB 698.0 kB/s eta 0:00:37
   ------------- -------------------------- 13.1/38.5 MB 698.0 kB/s eta 0:00:37
   ------------- -------------------------- 13.4/38.5 MB 694.9 kB/s eta 0:00:37
   -------------- ------------------------- 13.6/38.5 MB 702.4 kB/s eta 0:00:36
   -------------- ------------------------- 13.9/38.5 MB 709.1 kB/s eta 0:00:35
   -------------- ------------------------- 14.2/38.5 MB 716.0 kB/s eta 0:00:35
   -------------- ------------------------- 14.2/38.5 MB 716.0 kB/s eta 0:00:35
   -------------- ------------------------- 14.2/38.5 MB 716.0 kB/s eta 0:00:35
   -------------- ------------------------- 14.4/38.5 MB 704.9 kB/s eta 0:00:35
   --------------- ------------------------ 14.7/38.5 MB 707.6 kB/s eta 0:00:34
   --------------- ------------------------ 14.7/38.5 MB 707.6 kB/s eta 0:00:34
   --------------- ------------------------ 14.7/38.5 MB 707.6 kB/s eta 0:00:34
   --------------- ------------------------ 14.7/38.5 MB 707.6 kB/s eta 0:00:34
   --------------- ------------------------ 14.9/38.5 MB 696.9 kB/s eta 0:00:34
   --------------- ------------------------ 14.9/38.5 MB 696.9 kB/s eta 0:00:34
   --------------- ------------------------ 14.9/38.5 MB 696.9 kB/s eta 0:00:34

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=(0))

from sklearn.linear_model import LogisticRegression
m1=LogisticRegression()
m1.fit(x_train, y_train)
y_pred=m1.predict(x_test)

from sklearn.metrics import accuracy_score,confusion_matrix
acc=accuracy_score(y_test, y_pred)
c=confusion_matrix(y_test,y_pred)
print(acc)
print(c)

0.8506493506493507
[[ 23  20]
 [  3 108]]

C:\Users\jacob\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(